;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.DisruptorUtility",DevComment="")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.EnforcerUtility",DevComment="")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.MechAttack",DevComment="")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.MechMeleeAttack",DevComment="")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.RangerUtility",DevComment="Cooldown tag for ranger utility ability")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.TankAttack",DevComment="")
+GameplayTagList=(Tag="ComplyTags.Abilities.Cooldowns.TankChargeAttack",DevComment="")

