#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace ComplyTags
{
	namespace ComplyAbilities
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Primary)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Utility)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Throwable)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprint)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Reload)
		
		namespace AssetTags
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(ApplyShieldedEffectAbility)
			
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Primary)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Throwable)
		}
		
		namespace InputTags
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Primary)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_OneShotUtility)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Reload)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint)
		}
		
		namespace DamageTypes
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Physical)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Electrical)
		}
	}
	
	namespace States
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Firing)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_FiringBlocked)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Shielded)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Distracted)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Equipping)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_TotemBuffed)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Sprinting)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Slowed)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reviving)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Downed)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ThrowablePreparing)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ThrowableThrowing)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_NoThrowables)
	}
	
	namespace SetByCaller
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_ReduceRifleReserveAmmo)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_ReduceMagnumReserveAmmo)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_ReduceShotgunReserveAmmo)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_TotemSpeedBuff)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_TurretRecharge)

		namespace Stats
		{
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MaxHealth)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MaxArmor)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MaxArmorPenetration)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MovementSpeed)
			
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_RifleMaxAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_RifleMaxReserveAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_PlasmaGrenadeMaxCharges)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MagnumMaxAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_MagnumMaxReserveAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_TurretMaxCharges)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_ShotgunMaxAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_ShotgunMaxReserveAmmo)
			UE_DECLARE_GAMEPLAY_TAG_EXTERN(SBC_DecoyGrenadeMaxCharges)
		}
	}
	
	namespace Events
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_MeleeAttackRobot)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AttackTank)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ChargeAttackTank)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AttackMech)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_RevivePlayer)
	}
	
	namespace GameplayCues
	{
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitscanWeaponImpact)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShotgunImpact)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitscanWeaponFire)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponDryFire)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponReload)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponReloadFinished)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerHit)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerDeath)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShieldPlaced)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShieldHitscanWeaponImpact)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ShieldShotgunImpact)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PullGrenadePin)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ThrowGrenade)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExplodeGrenade)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GrapplingHookUse)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GrapplingHookImpact)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(GrapplingHookHooking)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurretTyping)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurretFire)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TurretImpact)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetableActorTakeDamage)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(TargetableActorDeath)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuffTotemApplyBuff)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(BuffTotemBuffAura)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnemyAttack)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(EnemyDeath)
		
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerReviveStart)
		UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerReviveEnd)
	}
}
